#!/usr/bin/env bash

echo -e "Hello, "$USER". This script will help you setup a Cloudfront Distribution for a Customer.io HTTPS link tracking proxy and request a SSL Certificate for the subdomain that you choose.\n"

echo -n "Enter your link tracking subdomain [ENTER]: "
read subdomain

echo -n "Enter your Customer.io tracking domain [ENTER]: "
read tracking_domain

echo "Which validation method would you like to use for your SSL Certificate? "
cat << METHODS
EMAIL
DNS
METHODS
echo -n "Which would you like to use? "
read validation_method

echo -n "Enter a CloudFormation stack name [customerio-proxy] [ENTER]: "
read stack_name

if [ "$stack_name" == "" ]; then
  stack_name="customerio-proxy"
fi

echo -e "Creating stack...\n"

aws cloudformation create-stack --region us-east-1 --template-body file://template.yml --stack-name ${stack_name} --parameters ParameterKey=LinkTrackingSubdomain,ParameterValue="${subdomain}" ParameterKey=TrackingDomain,ParameterValue=${tracking_domain} ParameterKey=ValidationMethod,ParameterValue=${validation_method}

echo -e "\nTime to validate your Certificate. This needs to be complete before the Cloudfront distribution will be created...\n"

if [ "$validation_method" == "EMAIL" ]; then
  echo "Check your domain administrator’s email account for an email from Amazon to accept..."
fi

echo -e "For more information on the next steps to validate your certificate, go to https://console.aws.amazon.com/acm/home\n"
